In [4]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd

In [9]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',')
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [10]:
print("x_data", x_data)
print("y_data", y_data)

x_data [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
y_data [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [11]:
model = Sequential()
model.add(Dense(input_dim=3, units=1))

W0314 18:33:15.421856  4312 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0314 18:33:15.437791  4312 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0314 18:33:15.440815  4312 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [12]:
model.compile(loss='mse', optimizer='rmsprop')
model.fit(x_data, y_data, epochs=2000)

W0314 18:33:20.294487  4312 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0314 18:33:20.400519  4312 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

W0314 18:33:20.408489  4312 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1020: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Epoch 1/2000
25/25 [==============================] - 0s 4ms/step - loss: 17616.8574
Epoch 2/2000
25/25 [==============================] - 0s 40us/step - loss: 17413.4863
Epoch 3/2000
25/25 [==============================] - 0s 38us/step - loss: 17267.0918
Epoch 4/2000
25/25 [==============================] - 0s 40us/step - loss: 17145.1934
Epoch 5/2000
25/25 [==============================] - 0s 80us/step - loss: 17037.4785
Epoch 6/2000
25/25 [==============================] - 0s 120us/step - loss: 16939.1699
Epoch 7/2000
25/25 [==============================] - 0s 40us/step - loss: 16847.6016
Epoch 8/2000
25/25 [==============================] - 0s 80us/step - loss: 16761.1172
Epoch 9/2000
25/25 [==============================] - 0s 66us/step - loss: 16678.6094
Epoch 10/2000
25/25 [==============================] - 0s 40us/step - loss: 16599.2969
Epoch 11/2000
25/25 [==============================] - 0s 80us/step - loss: 16522.6055
Epoch 12/2000
25/25 [==============================]

Epoch 96/2000
25/25 [==============================] - 0s 40us/step - loss: 11625.0625
Epoch 97/2000
25/25 [==============================] - 0s 80us/step - loss: 11573.8115
Epoch 98/2000
25/25 [==============================] - 0s 80us/step - loss: 11522.6758
Epoch 99/2000
25/25 [==============================] - 0s 40us/step - loss: 11471.6562
Epoch 100/2000
25/25 [==============================] - 0s 40us/step - loss: 11420.7539
Epoch 101/2000
25/25 [==============================] - 0s 80us/step - loss: 11369.9678
Epoch 102/2000
25/25 [==============================] - 0s 46us/step - loss: 11319.2959
Epoch 103/2000
25/25 [==============================] - 0s 80us/step - loss: 11268.7422
Epoch 104/2000
25/25 [==============================] - 0s 79us/step - loss: 11218.3047
Epoch 105/2000
25/25 [==============================] - 0s 40us/step - loss: 11167.9824
Epoch 106/2000
25/25 [==============================] - 0s 40us/step - loss: 11117.7764
Epoch 107/2000
25/25 [==============

Epoch 190/2000
25/25 [==============================] - 0s 40us/step - loss: 7314.2275
Epoch 191/2000
25/25 [==============================] - 0s 80us/step - loss: 7273.8643
Epoch 192/2000
25/25 [==============================] - 0s 80us/step - loss: 7233.6162
Epoch 193/2000
25/25 [==============================] - 0s 80us/step - loss: 7193.4858
Epoch 194/2000
25/25 [==============================] - 0s 0us/step - loss: 7153.4683
Epoch 195/2000
25/25 [==============================] - 0s 40us/step - loss: 7113.5654
Epoch 196/2000
25/25 [==============================] - 0s 0us/step - loss: 7073.7793
Epoch 197/2000
25/25 [==============================] - 0s 80us/step - loss: 7034.1074
Epoch 198/2000
25/25 [==============================] - 0s 35us/step - loss: 6994.5537
Epoch 199/2000
25/25 [==============================] - 0s 40us/step - loss: 6955.1133
Epoch 200/2000
25/25 [==============================] - 0s 40us/step - loss: 6915.7900
Epoch 201/2000
25/25 [=======================

Epoch 285/2000
25/25 [==============================] - 0s 40us/step - loss: 3993.9248
Epoch 286/2000
25/25 [==============================] - 0s 40us/step - loss: 3964.4856
Epoch 287/2000
25/25 [==============================] - 0s 39us/step - loss: 3935.1604
Epoch 288/2000
25/25 [==============================] - 0s 40us/step - loss: 3905.9497
Epoch 289/2000
25/25 [==============================] - 0s 40us/step - loss: 3876.8530
Epoch 290/2000
25/25 [==============================] - 0s 40us/step - loss: 3847.8716
Epoch 291/2000
25/25 [==============================] - 0s 40us/step - loss: 3819.0046
Epoch 292/2000
25/25 [==============================] - 0s 40us/step - loss: 3790.2510
Epoch 293/2000
25/25 [==============================] - 0s 40us/step - loss: 3761.6118
Epoch 294/2000
25/25 [==============================] - 0s 40us/step - loss: 3733.0862
Epoch 295/2000
25/25 [==============================] - 0s 40us/step - loss: 3704.6748
Epoch 296/2000
25/25 [=====================

Epoch 380/2000
25/25 [==============================] - 0s 40us/step - loss: 1705.2574
Epoch 381/2000
25/25 [==============================] - 0s 120us/step - loss: 1686.5938
Epoch 382/2000
25/25 [==============================] - 0s 40us/step - loss: 1668.0422
Epoch 383/2000
25/25 [==============================] - 0s 40us/step - loss: 1649.6019
Epoch 384/2000
25/25 [==============================] - 0s 40us/step - loss: 1631.2742
Epoch 385/2000
25/25 [==============================] - 0s 80us/step - loss: 1613.0585
Epoch 386/2000
25/25 [==============================] - 0s 80us/step - loss: 1594.9550
Epoch 387/2000
25/25 [==============================] - 0s 80us/step - loss: 1576.9633
Epoch 388/2000
25/25 [==============================] - 0s 80us/step - loss: 1559.0830
Epoch 389/2000
25/25 [==============================] - 0s 80us/step - loss: 1541.3152
Epoch 390/2000
25/25 [==============================] - 0s 80us/step - loss: 1523.6586
Epoch 391/2000
25/25 [====================

Epoch 475/2000
25/25 [==============================] - 0s 40us/step - loss: 426.0186
Epoch 476/2000
25/25 [==============================] - 0s 40us/step - loss: 417.7563
Epoch 477/2000
25/25 [==============================] - 0s 40us/step - loss: 409.5995
Epoch 478/2000
25/25 [==============================] - 0s 37us/step - loss: 401.5474
Epoch 479/2000
25/25 [==============================] - 0s 80us/step - loss: 393.6003
Epoch 480/2000
25/25 [==============================] - 0s 40us/step - loss: 385.7582
Epoch 481/2000
25/25 [==============================] - 0s 40us/step - loss: 378.0207
Epoch 482/2000
25/25 [==============================] - 0s 40us/step - loss: 370.3870
Epoch 483/2000
25/25 [==============================] - 0s 80us/step - loss: 362.8580
Epoch 484/2000
25/25 [==============================] - 0s 40us/step - loss: 355.4325
Epoch 485/2000
25/25 [==============================] - 0s 40us/step - loss: 348.1118
Epoch 486/2000
25/25 [==============================] 

Epoch 571/2000
25/25 [==============================] - 0s 40us/step - loss: 67.5741
Epoch 572/2000
25/25 [==============================] - 0s 40us/step - loss: 67.3825
Epoch 573/2000
25/25 [==============================] - 0s 40us/step - loss: 67.2160
Epoch 574/2000
25/25 [==============================] - 0s 40us/step - loss: 67.0722
Epoch 575/2000
25/25 [==============================] - 0s 40us/step - loss: 66.9486
Epoch 576/2000
25/25 [==============================] - 0s 0us/step - loss: 66.8431
Epoch 577/2000
25/25 [==============================] - 0s 40us/step - loss: 66.7532
Epoch 578/2000
25/25 [==============================] - 0s 80us/step - loss: 66.6768
Epoch 579/2000
25/25 [==============================] - 0s 40us/step - loss: 66.6120
Epoch 580/2000
25/25 [==============================] - 0s 80us/step - loss: 66.5568
Epoch 581/2000
25/25 [==============================] - 0s 40us/step - loss: 66.5095
Epoch 582/2000
25/25 [==============================] - 0s 0us/ste

Epoch 668/2000
25/25 [==============================] - 0s 40us/step - loss: 60.4933
Epoch 669/2000
25/25 [==============================] - 0s 0us/step - loss: 60.4077
Epoch 670/2000
25/25 [==============================] - 0s 40us/step - loss: 60.3219
Epoch 671/2000
25/25 [==============================] - 0s 40us/step - loss: 60.2361
Epoch 672/2000
25/25 [==============================] - 0s 40us/step - loss: 60.1501
Epoch 673/2000
25/25 [==============================] - 0s 6us/step - loss: 60.0640
Epoch 674/2000
25/25 [==============================] - 0s 40us/step - loss: 59.9778
Epoch 675/2000
25/25 [==============================] - 0s 40us/step - loss: 59.8917
Epoch 676/2000
25/25 [==============================] - 0s 39us/step - loss: 59.8056
Epoch 677/2000
25/25 [==============================] - 0s 60us/step - loss: 59.7201
Epoch 678/2000
25/25 [==============================] - 0s 80us/step - loss: 59.6351
Epoch 679/2000
25/25 [==============================] - 0s 80us/ste

Epoch 765/2000
25/25 [==============================] - 0s 40us/step - loss: 52.5623
Epoch 766/2000
25/25 [==============================] - 0s 80us/step - loss: 52.4842
Epoch 767/2000
25/25 [==============================] - 0s 80us/step - loss: 52.4072
Epoch 768/2000
25/25 [==============================] - 0s 80us/step - loss: 52.3291
Epoch 769/2000
25/25 [==============================] - 0s 40us/step - loss: 52.2523
Epoch 770/2000
25/25 [==============================] - 0s 40us/step - loss: 52.1744
Epoch 771/2000
25/25 [==============================] - 0s 81us/step - loss: 52.0977
Epoch 772/2000
25/25 [==============================] - 0s 40us/step - loss: 52.0201
Epoch 773/2000
25/25 [==============================] - 0s 40us/step - loss: 51.9435
Epoch 774/2000
25/25 [==============================] - 0s 40us/step - loss: 51.8660
Epoch 775/2000
25/25 [==============================] - 0s 39us/step - loss: 51.7896
Epoch 776/2000
25/25 [==============================] - 0s 67us/s

Epoch 862/2000
25/25 [==============================] - 0s 40us/step - loss: 45.4102
Epoch 863/2000
25/25 [==============================] - 0s 40us/step - loss: 45.3410
Epoch 864/2000
25/25 [==============================] - 0s 39us/step - loss: 45.2707
Epoch 865/2000
25/25 [==============================] - 0s 40us/step - loss: 45.2016
Epoch 866/2000
25/25 [==============================] - 0s 40us/step - loss: 45.1314
Epoch 867/2000
25/25 [==============================] - 0s 40us/step - loss: 45.0626
Epoch 868/2000
25/25 [==============================] - 0s 40us/step - loss: 44.9925
Epoch 869/2000
25/25 [==============================] - 0s 40us/step - loss: 44.9238
Epoch 870/2000
25/25 [==============================] - 0s 81us/step - loss: 44.8539
Epoch 871/2000
25/25 [==============================] - 0s 40us/step - loss: 44.7854
Epoch 872/2000
25/25 [==============================] - 0s 40us/step - loss: 44.7156
Epoch 873/2000
25/25 [==============================] - 0s 40us/s

Epoch 959/2000
25/25 [==============================] - 0s 39us/step - loss: 38.9975
Epoch 960/2000
25/25 [==============================] - 0s 40us/step - loss: 38.9343
Epoch 961/2000
25/25 [==============================] - 0s 40us/step - loss: 38.8727
Epoch 962/2000
25/25 [==============================] - 0s 40us/step - loss: 38.8097
Epoch 963/2000
25/25 [==============================] - 0s 76us/step - loss: 38.7482
Epoch 964/2000
25/25 [==============================] - 0s 40us/step - loss: 38.6854
Epoch 965/2000
25/25 [==============================] - 0s 40us/step - loss: 38.6241
Epoch 966/2000
25/25 [==============================] - 0s 40us/step - loss: 38.5614
Epoch 967/2000
25/25 [==============================] - 0s 94us/step - loss: 38.5002
Epoch 968/2000
25/25 [==============================] - 0s 80us/step - loss: 38.4377
Epoch 969/2000
25/25 [==============================] - 0s 80us/step - loss: 38.3766
Epoch 970/2000
25/25 [==============================] - 0s 80us/s

Epoch 1055/2000
25/25 [==============================] - 0s 40us/step - loss: 33.3373
Epoch 1056/2000
25/25 [==============================] - 0s 40us/step - loss: 33.2811
Epoch 1057/2000
25/25 [==============================] - 0s 0us/step - loss: 33.2264
Epoch 1058/2000
25/25 [==============================] - 0s 40us/step - loss: 33.1703
Epoch 1059/2000
25/25 [==============================] - 0s 40us/step - loss: 33.1158
Epoch 1060/2000
25/25 [==============================] - 0s 81us/step - loss: 33.0598
Epoch 1061/2000
25/25 [==============================] - 0s 39us/step - loss: 33.0054
Epoch 1062/2000
25/25 [==============================] - 0s 80us/step - loss: 32.9496
Epoch 1063/2000
25/25 [==============================] - 0s 80us/step - loss: 32.8954
Epoch 1064/2000
25/25 [==============================] - 0s 40us/step - loss: 32.8396
Epoch 1065/2000
25/25 [==============================] - 0s 39us/step - loss: 32.7856
Epoch 1066/2000
25/25 [==============================] 

Epoch 1151/2000
25/25 [==============================] - 0s 40us/step - loss: 28.3270
Epoch 1152/2000
25/25 [==============================] - 0s 80us/step - loss: 28.2773
Epoch 1153/2000
25/25 [==============================] - 0s 40us/step - loss: 28.2293
Epoch 1154/2000
25/25 [==============================] - 0s 40us/step - loss: 28.1797
Epoch 1155/2000
25/25 [==============================] - 0s 0us/step - loss: 28.1319
Epoch 1156/2000
25/25 [==============================] - 0s 40us/step - loss: 28.0825
Epoch 1157/2000
25/25 [==============================] - 0s 80us/step - loss: 28.0348
Epoch 1158/2000
25/25 [==============================] - 0s 40us/step - loss: 27.9855
Epoch 1159/2000
25/25 [==============================] - 0s 40us/step - loss: 27.9379
Epoch 1160/2000
25/25 [==============================] - 0s 40us/step - loss: 27.8888
Epoch 1161/2000
25/25 [==============================] - 0s 71us/step - loss: 27.8413
Epoch 1162/2000
25/25 [==============================] 

Epoch 1247/2000
25/25 [==============================] - 0s 40us/step - loss: 23.9408
Epoch 1248/2000
25/25 [==============================] - 0s 40us/step - loss: 23.8975
Epoch 1249/2000
25/25 [==============================] - 0s 40us/step - loss: 23.8559
Epoch 1250/2000
25/25 [==============================] - 0s 40us/step - loss: 23.8127
Epoch 1251/2000
25/25 [==============================] - 0s 0us/step - loss: 23.7713
Epoch 1252/2000
25/25 [==============================] - 0s 40us/step - loss: 23.7282
Epoch 1253/2000
25/25 [==============================] - 0s 40us/step - loss: 23.6869
Epoch 1254/2000
25/25 [==============================] - 0s 40us/step - loss: 23.6440
Epoch 1255/2000
25/25 [==============================] - 0s 40us/step - loss: 23.6028
Epoch 1256/2000
25/25 [==============================] - 0s 43us/step - loss: 23.5601
Epoch 1257/2000
25/25 [==============================] - 0s 40us/step - loss: 23.5190
Epoch 1258/2000
25/25 [==============================] 

Epoch 1343/2000
25/25 [==============================] - 0s 40us/step - loss: 20.1605
Epoch 1344/2000
25/25 [==============================] - 0s 40us/step - loss: 20.1234
Epoch 1345/2000
25/25 [==============================] - 0s 40us/step - loss: 20.0880
Epoch 1346/2000
25/25 [==============================] - 0s 40us/step - loss: 20.0511
Epoch 1347/2000
25/25 [==============================] - 0s 80us/step - loss: 20.0159
Epoch 1348/2000
25/25 [==============================] - 0s 75us/step - loss: 19.9791
Epoch 1349/2000
25/25 [==============================] - 0s 40us/step - loss: 19.9440
Epoch 1350/2000
25/25 [==============================] - 0s 80us/step - loss: 19.9073
Epoch 1351/2000
25/25 [==============================] - 0s 51us/step - loss: 19.8724
Epoch 1352/2000
25/25 [==============================] - 0s 80us/step - loss: 19.8358
Epoch 1353/2000
25/25 [==============================] - 0s 39us/step - loss: 19.8010
Epoch 1354/2000
25/25 [==============================]

Epoch 1439/2000
25/25 [==============================] - 0s 39us/step - loss: 16.9721
Epoch 1440/2000
25/25 [==============================] - 0s 40us/step - loss: 16.9412
Epoch 1441/2000
25/25 [==============================] - 0s 40us/step - loss: 16.9119
Epoch 1442/2000
25/25 [==============================] - 0s 40us/step - loss: 16.8811
Epoch 1443/2000
25/25 [==============================] - 0s 40us/step - loss: 16.8519
Epoch 1444/2000
25/25 [==============================] - 0s 80us/step - loss: 16.8212
Epoch 1445/2000
25/25 [==============================] - 0s 40us/step - loss: 16.7922
Epoch 1446/2000
25/25 [==============================] - 0s 40us/step - loss: 16.7616
Epoch 1447/2000
25/25 [==============================] - 0s 40us/step - loss: 16.7327
Epoch 1448/2000
25/25 [==============================] - 0s 160us/step - loss: 16.7023
Epoch 1449/2000
25/25 [==============================] - 0s 40us/step - loss: 16.6734
Epoch 1450/2000
25/25 [==============================

Epoch 1535/2000
25/25 [==============================] - 0s 39us/step - loss: 14.3597
Epoch 1536/2000
25/25 [==============================] - 0s 40us/step - loss: 14.3348
Epoch 1537/2000
25/25 [==============================] - 0s 40us/step - loss: 14.3112
Epoch 1538/2000
25/25 [==============================] - 0s 80us/step - loss: 14.2864
Epoch 1539/2000
25/25 [==============================] - 0s 40us/step - loss: 14.2630
Epoch 1540/2000
25/25 [==============================] - 0s 40us/step - loss: 14.2383
Epoch 1541/2000
25/25 [==============================] - 0s 80us/step - loss: 14.2150
Epoch 1542/2000
25/25 [==============================] - 0s 40us/step - loss: 14.1904
Epoch 1543/2000
25/25 [==============================] - 0s 40us/step - loss: 14.1672
Epoch 1544/2000
25/25 [==============================] - 0s 40us/step - loss: 14.1428
Epoch 1545/2000
25/25 [==============================] - 0s 40us/step - loss: 14.1197
Epoch 1546/2000
25/25 [==============================]

Epoch 1631/2000
25/25 [==============================] - 0s 40us/step - loss: 12.2934
Epoch 1632/2000
25/25 [==============================] - 0s 41us/step - loss: 12.2740
Epoch 1633/2000
25/25 [==============================] - 0s 39us/step - loss: 12.2558
Epoch 1634/2000
25/25 [==============================] - 0s 40us/step - loss: 12.2366
Epoch 1635/2000
25/25 [==============================] - 0s 40us/step - loss: 12.2184
Epoch 1636/2000
25/25 [==============================] - 0s 80us/step - loss: 12.1993
Epoch 1637/2000
25/25 [==============================] - 0s 67us/step - loss: 12.1813
Epoch 1638/2000
25/25 [==============================] - 0s 40us/step - loss: 12.1622
Epoch 1639/2000
25/25 [==============================] - 0s 80us/step - loss: 12.1443
Epoch 1640/2000
25/25 [==============================] - 0s 81us/step - loss: 12.1254
Epoch 1641/2000
25/25 [==============================] - 0s 98us/step - loss: 12.1076
Epoch 1642/2000
25/25 [==============================]

Epoch 1727/2000
25/25 [==============================] - 0s 40us/step - loss: 10.7157
Epoch 1728/2000
25/25 [==============================] - 0s 40us/step - loss: 10.7012
Epoch 1729/2000
25/25 [==============================] - 0s 34us/step - loss: 10.6875
Epoch 1730/2000
25/25 [==============================] - 0s 80us/step - loss: 10.6730
Epoch 1731/2000
25/25 [==============================] - 0s 40us/step - loss: 10.6594
Epoch 1732/2000
25/25 [==============================] - 0s 40us/step - loss: 10.6450
Epoch 1733/2000
25/25 [==============================] - 0s 81us/step - loss: 10.6315
Epoch 1734/2000
25/25 [==============================] - 0s 40us/step - loss: 10.6172
Epoch 1735/2000
25/25 [==============================] - 0s 40us/step - loss: 10.6038
Epoch 1736/2000
25/25 [==============================] - 0s 80us/step - loss: 10.5896
Epoch 1737/2000
25/25 [==============================] - 0s 40us/step - loss: 10.5762
Epoch 1738/2000
25/25 [==============================]

Epoch 1823/2000
25/25 [==============================] - 0s 80us/step - loss: 9.5425
Epoch 1824/2000
25/25 [==============================] - 0s 40us/step - loss: 9.5318
Epoch 1825/2000
25/25 [==============================] - 0s 40us/step - loss: 9.5217
Epoch 1826/2000
25/25 [==============================] - 0s 40us/step - loss: 9.5111
Epoch 1827/2000
25/25 [==============================] - 0s 0us/step - loss: 9.5010
Epoch 1828/2000
25/25 [==============================] - 0s 40us/step - loss: 9.4905
Epoch 1829/2000
25/25 [==============================] - 0s 40us/step - loss: 9.4805
Epoch 1830/2000
25/25 [==============================] - 0s 80us/step - loss: 9.4700
Epoch 1831/2000
25/25 [==============================] - 0s 64us/step - loss: 9.4601
Epoch 1832/2000
25/25 [==============================] - 0s 79us/step - loss: 9.4497
Epoch 1833/2000
25/25 [==============================] - 0s 80us/step - loss: 9.4398
Epoch 1834/2000
25/25 [==============================] - 0s 40us/s

Epoch 1920/2000
25/25 [==============================] - 0s 80us/step - loss: 8.6745
Epoch 1921/2000
25/25 [==============================] - 0s 0us/step - loss: 8.6671
Epoch 1922/2000
25/25 [==============================] - 0s 40us/step - loss: 8.6594
Epoch 1923/2000
25/25 [==============================] - 0s 30us/step - loss: 8.6520
Epoch 1924/2000
25/25 [==============================] - 0s 40us/step - loss: 8.6443
Epoch 1925/2000
25/25 [==============================] - 0s 40us/step - loss: 8.6370
Epoch 1926/2000
25/25 [==============================] - 0s 40us/step - loss: 8.6294
Epoch 1927/2000
25/25 [==============================] - 0s 40us/step - loss: 8.6221
Epoch 1928/2000
25/25 [==============================] - 0s 61us/step - loss: 8.6145
Epoch 1929/2000
25/25 [==============================] - 0s 80us/step - loss: 8.6073
Epoch 1930/2000
25/25 [==============================] - 0s 40us/step - loss: 8.5998
Epoch 1931/2000
25/25 [==============================] - 0s 40us/s

In [13]:
print("0, 2, 1", model.predict(np.array([[0, 2, 1]])))
print("0, 9, -1", model.predict(np.array([[0, 9, -1]])))

0, 2, 1 [[2.9327753]]
0, 9, -1 [[4.9119043]]
