In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils
import numpy as np

In [3]:
# Predicting animal type based on various features
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]] - 1
print(x_data.shape, y_data.shape)

(101, 16) (101, 1)


In [6]:
nb_classes = 7
y_one_hot = np_utils.to_categorical(y_data, nb_classes)
print(y_one_hot[:5])

[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [7]:
model = Sequential()
model.add(Dense(nb_classes, input_shape=(16,)))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
model.summary()

W0314 18:42:16.895501 15184 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0314 18:42:16.911458 15184 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0314 18:42:16.914418 15184 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0314 18:42:16.933366 15184 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0314 18:42:16.955342 15184 deprecation_wrapper.py:119] From C:\Users\Admin\Anac

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 7)                 119       
_________________________________________________________________
activation_1 (Activation)    (None, 7)                 0         
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________


In [8]:
history = model.fit(x_data, y_one_hot, epochs=1000)

W0314 18:42:18.480375 15184 deprecation.py:323] From C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0314 18:42:18.524276 15184 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/1000
101/101 [==============================] - 0s 1ms/step - loss: 2.2170 - acc: 0.0990
Epoch 2/1000
101/101 [==============================] - 0s 79us/step - loss: 2.0982 - acc: 0.1287
Epoch 3/1000
101/101 [==============================] - 0s 75us/step - loss: 2.0033 - acc: 0.2079
Epoch 4/1000
101/101 [==============================] - 0s 74us/step - loss: 1.9007 - acc: 0.4356
Epoch 5/1000
101/101 [==============================] - 0s 69us/step - loss: 1.8290 - acc: 0.4752
Epoch 6/1000
101/101 [==============================] - 0s 69us/step - loss: 1.7734 - acc: 0.4950
Epoch 7/1000
101/101 [==============================] - 0s 69us/step - loss: 1.7016 - acc: 0.5149
Epoch 8/1000
101/101 [==============================] - 0s 60us/step - loss: 1.6465 - acc: 0.5149
Epoch 9/1000
101/101 [==============================] - 0s 59us/step - loss: 1.6062 - acc: 0.5248
Epoch 10/1000
101/101 [==============================] - 0s 49us/step - loss: 1.5662 - acc: 0.5446
Epoch 11/1000
101/10

101/101 [==============================] - 0s 59us/step - loss: 0.8188 - acc: 0.8317
Epoch 84/1000
101/101 [==============================] - 0s 47us/step - loss: 0.8142 - acc: 0.8515
Epoch 85/1000
101/101 [==============================] - 0s 59us/step - loss: 0.8100 - acc: 0.8515
Epoch 86/1000
101/101 [==============================] - 0s 40us/step - loss: 0.8054 - acc: 0.8416
Epoch 87/1000
101/101 [==============================] - 0s 47us/step - loss: 0.8013 - acc: 0.8515
Epoch 88/1000
101/101 [==============================] - 0s 59us/step - loss: 0.7966 - acc: 0.8614
Epoch 89/1000
101/101 [==============================] - 0s 59us/step - loss: 0.7930 - acc: 0.8614
Epoch 90/1000
101/101 [==============================] - 0s 49us/step - loss: 0.7896 - acc: 0.8416
Epoch 91/1000
101/101 [==============================] - 0s 59us/step - loss: 0.7854 - acc: 0.8416
Epoch 92/1000
101/101 [==============================] - 0s 58us/step - loss: 0.7803 - acc: 0.8713
Epoch 93/1000
101/101 [=

101/101 [==============================] - 0s 48us/step - loss: 0.5913 - acc: 0.8713
Epoch 165/1000
101/101 [==============================] - 0s 59us/step - loss: 0.5891 - acc: 0.8614
Epoch 166/1000
101/101 [==============================] - 0s 51us/step - loss: 0.5873 - acc: 0.8614
Epoch 167/1000
101/101 [==============================] - 0s 59us/step - loss: 0.5854 - acc: 0.8614
Epoch 168/1000
101/101 [==============================] - 0s 49us/step - loss: 0.5838 - acc: 0.8614
Epoch 169/1000
101/101 [==============================] - 0s 89us/step - loss: 0.5817 - acc: 0.8614
Epoch 170/1000
101/101 [==============================] - 0s 49us/step - loss: 0.5799 - acc: 0.8614
Epoch 171/1000
101/101 [==============================] - 0s 69us/step - loss: 0.5788 - acc: 0.8614
Epoch 172/1000
101/101 [==============================] - 0s 48us/step - loss: 0.5763 - acc: 0.8614
Epoch 173/1000
101/101 [==============================] - 0s 49us/step - loss: 0.5749 - acc: 0.8614
Epoch 174/1000


101/101 [==============================] - 0s 62us/step - loss: 0.4823 - acc: 0.8614
Epoch 247/1000
101/101 [==============================] - 0s 59us/step - loss: 0.4810 - acc: 0.8614
Epoch 248/1000
101/101 [==============================] - 0s 58us/step - loss: 0.4803 - acc: 0.8614
Epoch 249/1000
101/101 [==============================] - 0s 55us/step - loss: 0.4793 - acc: 0.8614
Epoch 250/1000
101/101 [==============================] - 0s 49us/step - loss: 0.4786 - acc: 0.8614
Epoch 251/1000
101/101 [==============================] - 0s 49us/step - loss: 0.4775 - acc: 0.8614
Epoch 252/1000
101/101 [==============================] - 0s 43us/step - loss: 0.4762 - acc: 0.8614
Epoch 253/1000
101/101 [==============================] - 0s 59us/step - loss: 0.4753 - acc: 0.8614
Epoch 254/1000
101/101 [==============================] - 0s 40us/step - loss: 0.4747 - acc: 0.8614
Epoch 255/1000
101/101 [==============================] - 0s 50us/step - loss: 0.4741 - acc: 0.8614
Epoch 256/1000


101/101 [==============================] - 0s 59us/step - loss: 0.4136 - acc: 0.8911
Epoch 329/1000
101/101 [==============================] - 0s 69us/step - loss: 0.4130 - acc: 0.8911
Epoch 330/1000
101/101 [==============================] - 0s 67us/step - loss: 0.4124 - acc: 0.8911
Epoch 331/1000
101/101 [==============================] - 0s 45us/step - loss: 0.4116 - acc: 0.8911
Epoch 332/1000
101/101 [==============================] - 0s 85us/step - loss: 0.4110 - acc: 0.8911
Epoch 333/1000
101/101 [==============================] - 0s 59us/step - loss: 0.4101 - acc: 0.8911
Epoch 334/1000
101/101 [==============================] - 0s 49us/step - loss: 0.4097 - acc: 0.8911
Epoch 335/1000
101/101 [==============================] - 0s 79us/step - loss: 0.4092 - acc: 0.8911
Epoch 336/1000
101/101 [==============================] - 0s 55us/step - loss: 0.4083 - acc: 0.8911
Epoch 337/1000
101/101 [==============================] - 0s 79us/step - loss: 0.4076 - acc: 0.8911
Epoch 338/1000


101/101 [==============================] - 0s 59us/step - loss: 0.3664 - acc: 0.9109
Epoch 410/1000
101/101 [==============================] - 0s 68us/step - loss: 0.3659 - acc: 0.9109
Epoch 411/1000
101/101 [==============================] - 0s 59us/step - loss: 0.3654 - acc: 0.9109
Epoch 412/1000
101/101 [==============================] - 0s 69us/step - loss: 0.3652 - acc: 0.9109
Epoch 413/1000
101/101 [==============================] - 0s 59us/step - loss: 0.3647 - acc: 0.9109
Epoch 414/1000
101/101 [==============================] - 0s 59us/step - loss: 0.3645 - acc: 0.9109
Epoch 415/1000
101/101 [==============================] - 0s 45us/step - loss: 0.3638 - acc: 0.9109
Epoch 416/1000
101/101 [==============================] - 0s 79us/step - loss: 0.3635 - acc: 0.9109
Epoch 417/1000
101/101 [==============================] - 0s 49us/step - loss: 0.3625 - acc: 0.9109
Epoch 418/1000
101/101 [==============================] - 0s 69us/step - loss: 0.3624 - acc: 0.9109
Epoch 419/1000


101/101 [==============================] - 0s 79us/step - loss: 0.3299 - acc: 0.9406
Epoch 491/1000
101/101 [==============================] - 0s 59us/step - loss: 0.3297 - acc: 0.9406
Epoch 492/1000
101/101 [==============================] - 0s 69us/step - loss: 0.3294 - acc: 0.9406
Epoch 493/1000
101/101 [==============================] - 0s 49us/step - loss: 0.3288 - acc: 0.9406
Epoch 494/1000
101/101 [==============================] - 0s 45us/step - loss: 0.3285 - acc: 0.9406
Epoch 495/1000
101/101 [==============================] - 0s 59us/step - loss: 0.3281 - acc: 0.9406
Epoch 496/1000
101/101 [==============================] - 0s 59us/step - loss: 0.3278 - acc: 0.9406
Epoch 497/1000
101/101 [==============================] - 0s 59us/step - loss: 0.3275 - acc: 0.9406
Epoch 498/1000
101/101 [==============================] - 0s 69us/step - loss: 0.3269 - acc: 0.9406
Epoch 499/1000
101/101 [==============================] - 0s 60us/step - loss: 0.3263 - acc: 0.9406
Epoch 500/1000


101/101 [==============================] - 0s 72us/step - loss: 0.3009 - acc: 0.9406
Epoch 572/1000
101/101 [==============================] - 0s 48us/step - loss: 0.3004 - acc: 0.9406
Epoch 573/1000
101/101 [==============================] - 0s 45us/step - loss: 0.3001 - acc: 0.9406
Epoch 574/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2997 - acc: 0.9406
Epoch 575/1000
101/101 [==============================] - 0s 69us/step - loss: 0.2993 - acc: 0.9406
Epoch 576/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2992 - acc: 0.9406
Epoch 577/1000
101/101 [==============================] - 0s 69us/step - loss: 0.2987 - acc: 0.9406
Epoch 578/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2986 - acc: 0.9406
Epoch 579/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2980 - acc: 0.9406
Epoch 580/1000
101/101 [==============================] - 0s 46us/step - loss: 0.2978 - acc: 0.9406
Epoch 581/1000


101/101 [==============================] - 0s 49us/step - loss: 0.2762 - acc: 0.9406
Epoch 654/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2761 - acc: 0.9406
Epoch 655/1000
101/101 [==============================] - 0s 65us/step - loss: 0.2757 - acc: 0.9406
Epoch 656/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2755 - acc: 0.9406
Epoch 657/1000
101/101 [==============================] - 0s 69us/step - loss: 0.2750 - acc: 0.9406
Epoch 658/1000
101/101 [==============================] - 0s 60us/step - loss: 0.2749 - acc: 0.9406
Epoch 659/1000
101/101 [==============================] - 0s 48us/step - loss: 0.2746 - acc: 0.9406
Epoch 660/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2744 - acc: 0.9406
Epoch 661/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2744 - acc: 0.9406
Epoch 662/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2740 - acc: 0.9406
Epoch 663/1000


101/101 [==============================] - 0s 40us/step - loss: 0.2563 - acc: 0.9406
Epoch 735/1000
101/101 [==============================] - 0s 48us/step - loss: 0.2558 - acc: 0.9406
Epoch 736/1000
101/101 [==============================] - 0s 58us/step - loss: 0.2558 - acc: 0.9406
Epoch 737/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2556 - acc: 0.9406
Epoch 738/1000
101/101 [==============================] - 0s 69us/step - loss: 0.2556 - acc: 0.9406
Epoch 739/1000
101/101 [==============================] - 0s 55us/step - loss: 0.2551 - acc: 0.9406
Epoch 740/1000
101/101 [==============================] - 0s 58us/step - loss: 0.2550 - acc: 0.9406
Epoch 741/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2545 - acc: 0.9406
Epoch 742/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2544 - acc: 0.9406
Epoch 743/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2541 - acc: 0.9406
Epoch 744/1000


101/101 [==============================] - 0s 40us/step - loss: 0.2390 - acc: 0.9505
Epoch 816/1000
101/101 [==============================] - 0s 69us/step - loss: 0.2388 - acc: 0.9505
Epoch 817/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2385 - acc: 0.9505
Epoch 818/1000
101/101 [==============================] - ETA: 0s - loss: 0.2221 - acc: 0.968 - 0s 59us/step - loss: 0.2384 - acc: 0.9505
Epoch 819/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2382 - acc: 0.9505
Epoch 820/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2380 - acc: 0.9505
Epoch 821/1000
101/101 [==============================] - 0s 40us/step - loss: 0.2380 - acc: 0.9505
Epoch 822/1000
101/101 [==============================] - 0s 56us/step - loss: 0.2377 - acc: 0.9505
Epoch 823/1000
101/101 [==============================] - 0s 54us/step - loss: 0.2375 - acc: 0.9505
Epoch 824/1000
101/101 [==============================] - 0s 40us/step - loss

101/101 [==============================] - 0s 59us/step - loss: 0.2239 - acc: 0.9604
Epoch 897/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2238 - acc: 0.9604
Epoch 898/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2238 - acc: 0.9604
Epoch 899/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2237 - acc: 0.9604
Epoch 900/1000
101/101 [==============================] - 0s 40us/step - loss: 0.2233 - acc: 0.9604
Epoch 901/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2232 - acc: 0.9604
Epoch 902/1000
101/101 [==============================] - 0s 56us/step - loss: 0.2229 - acc: 0.9604
Epoch 903/1000
101/101 [==============================] - 0s 40us/step - loss: 0.2227 - acc: 0.9604
Epoch 904/1000
101/101 [==============================] - 0s 67us/step - loss: 0.2225 - acc: 0.9604
Epoch 905/1000
101/101 [==============================] - 0s 55us/step - loss: 0.2226 - acc: 0.9604
Epoch 906/1000


101/101 [==============================] - 0s 49us/step - loss: 0.2109 - acc: 0.9505
Epoch 978/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2106 - acc: 0.9505
Epoch 979/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2103 - acc: 0.9505
Epoch 980/1000
101/101 [==============================] - 0s 56us/step - loss: 0.2103 - acc: 0.9505
Epoch 981/1000
101/101 [==============================] - 0s 68us/step - loss: 0.2101 - acc: 0.9505
Epoch 982/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2100 - acc: 0.9505
Epoch 983/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2099 - acc: 0.9505
Epoch 984/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2098 - acc: 0.9505
Epoch 985/1000
101/101 [==============================] - 0s 59us/step - loss: 0.2097 - acc: 0.9505
Epoch 986/1000
101/101 [==============================] - 0s 49us/step - loss: 0.2095 - acc: 0.9505
Epoch 987/1000


In [9]:
# Let's see if we can predict
pred = model.predict_classes(x_data)
for p, y in zip(pred, y_data):
    print("prediction: ", p, " true Y: ", y)

prediction:  6  true Y:  [-1.]
prediction:  6  true Y:  [-1.]
prediction:  2  true Y:  [2.]
prediction:  6  true Y:  [-1.]
prediction:  6  true Y:  [-1.]
prediction:  6  true Y:  [-1.]
prediction:  6  true Y:  [-1.]
prediction:  2  true Y:  [2.]
prediction:  2  true Y:  [2.]
prediction:  6  true Y:  [-1.]
prediction:  6  true Y:  [-1.]
prediction:  0  true Y:  [0.]
prediction:  2  true Y:  [2.]
prediction:  5  true Y:  [5.]
prediction:  5  true Y:  [5.]
prediction:  5  true Y:  [5.]
prediction:  0  true Y:  [0.]
prediction:  6  true Y:  [-1.]
prediction:  2  true Y:  [2.]
prediction:  6  true Y:  [-1.]
prediction:  0  true Y:  [0.]
prediction:  0  true Y:  [0.]
prediction:  6  true Y:  [-1.]
prediction:  0  true Y:  [0.]
prediction:  4  true Y:  [4.]
prediction:  3  true Y:  [3.]
prediction:  3  true Y:  [3.]
prediction:  6  true Y:  [-1.]
prediction:  6  true Y:  [-1.]
prediction:  6  true Y:  [-1.]
prediction:  4  true Y:  [4.]
prediction:  6  true Y:  [-1.]
prediction:  6  true Y:  