In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
import numpy as np
np.random.seed(2020)  # for reproducibility

In [3]:
x_data = np.array([[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5],
          [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]])
y_data = np.array([[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]])

In [4]:
# Evaluation our model using this test dataset
x_test = np.array([[2, 1, 1], [3, 1, 2], [3, 3, 4]])
y_test = np.array([[0, 0, 1], [0, 0, 1], [0, 0, 1]])

In [5]:
model = Sequential()
model.add(Dense(3, input_dim=3))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer=SGD(lr=0.1),
              metrics=['accuracy'])
model.summary()

W0314 18:44:45.462967  4240 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0314 18:44:45.479377  4240 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0314 18:44:45.482335  4240 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0314 18:44:45.511259  4240 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0314 18:44:45.525662  4240 deprecation_wrapper.py:119] From C:\Users\Admin\Anac

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 12        
_________________________________________________________________
activation_1 (Activation)    (None, 3)                 0         
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


In [7]:
history = model.fit(x_data, y_data, epochs=200)

W0314 18:45:02.913498  4240 deprecation.py:323] From C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0314 18:45:02.955535  4240 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/200
8/8 [==============================] - 0s 15ms/step - loss: 2.4604 - acc: 0.2500
Epoch 2/200
8/8 [==============================] - 0s 0us/step - loss: 1.4599 - acc: 0.2500
Epoch 3/200
8/8 [==============================] - 0s 732us/step - loss: 1.1238 - acc: 0.3750
Epoch 4/200
8/8 [==============================] - 0s 249us/step - loss: 1.1081 - acc: 0.2500
Epoch 5/200
8/8 [==============================] - 0s 125us/step - loss: 1.0994 - acc: 0.3750
Epoch 6/200
8/8 [==============================] - 0s 250us/step - loss: 1.0910 - acc: 0.3750
Epoch 7/200
8/8 [==============================] - 0s 277us/step - loss: 1.0830 - acc: 0.3750
Epoch 8/200
8/8 [==============================] - 0s 251us/step - loss: 1.0751 - acc: 0.3750
Epoch 9/200
8/8 [==============================] - 0s 249us/step - loss: 1.0675 - acc: 0.3750
Epoch 10/200
8/8 [==============================] - 0s 371us/step - loss: 1.0600 - acc: 0.3750
Epoch 11/200
8/8 [==============================] - 0s 249us/s

Epoch 88/200
8/8 [==============================] - 0s 249us/step - loss: 0.7479 - acc: 0.6250
Epoch 89/200
8/8 [==============================] - 0s 251us/step - loss: 0.7459 - acc: 0.6250
Epoch 90/200
8/8 [==============================] - 0s 248us/step - loss: 0.7438 - acc: 0.6250
Epoch 91/200
8/8 [==============================] - 0s 247us/step - loss: 0.7418 - acc: 0.6250
Epoch 92/200
8/8 [==============================] - 0s 249us/step - loss: 0.7398 - acc: 0.6250
Epoch 93/200
8/8 [==============================] - 0s 316us/step - loss: 0.7379 - acc: 0.6250
Epoch 94/200
8/8 [==============================] - 0s 124us/step - loss: 0.7359 - acc: 0.6250
Epoch 95/200
8/8 [==============================] - 0s 125us/step - loss: 0.7340 - acc: 0.6250
Epoch 96/200
8/8 [==============================] - 0s 249us/step - loss: 0.7321 - acc: 0.6250
Epoch 97/200
8/8 [==============================] - 0s 370us/step - loss: 0.7303 - acc: 0.6250
Epoch 98/200
8/8 [==============================] 

Epoch 174/200
8/8 [==============================] - 0s 124us/step - loss: 0.6317 - acc: 0.6250
Epoch 175/200
8/8 [==============================] - 0s 242us/step - loss: 0.6308 - acc: 0.6250
Epoch 176/200
8/8 [==============================] - 0s 125us/step - loss: 0.6299 - acc: 0.6250
Epoch 177/200
8/8 [==============================] - 0s 124us/step - loss: 0.6290 - acc: 0.6250
Epoch 178/200
8/8 [==============================] - 0s 208us/step - loss: 0.6281 - acc: 0.6250
Epoch 179/200
8/8 [==============================] - 0s 125us/step - loss: 0.6272 - acc: 0.6250
Epoch 180/200
8/8 [==============================] - 0s 125us/step - loss: 0.6264 - acc: 0.6250
Epoch 181/200
8/8 [==============================] - 0s 125us/step - loss: 0.6255 - acc: 0.6250
Epoch 182/200
8/8 [==============================] - 0s 249us/step - loss: 0.6246 - acc: 0.6250
Epoch 183/200
8/8 [==============================] - 0s 125us/step - loss: 0.6238 - acc: 0.6250
Epoch 184/200
8/8 [=====================

In [8]:
predictions = model.predict(x_test)
score = model.evaluate(x_test, y_test)

3/3 [==============================] - 0s 9ms/step


In [13]:
print(predictions)
print(score)

[[1.7984717e-03 9.9329716e-03 9.8826849e-01]
 [4.8011099e-04 3.1537975e-03 9.9636602e-01]
 [5.1288093e-03 1.8907974e-02 9.7596323e-01]]
[0.013257232494652271, 1.0]


In [9]:
print('Prediction: ', [np.argmax(prediction) for prediction in predictions])
print('Accuracy: ', score[1])

Prediction:  [2, 2, 2]
Accuracy:  1.0
