In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
import numpy as np
np.random.seed(2020)  # for reproducibility

Using TensorFlow backend.
C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [2]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [3]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [4]:
print(x_data)
print(y_data)

[[8.28659973e+02 8.33450012e+02 9.08100000e+05 8.28349976e+02]
 [8.23020020e+02 8.28070007e+02 1.82810000e+06 8.21655029e+02]
 [8.19929993e+02 8.24400024e+02 1.43810000e+06 8.18979980e+02]
 [8.16000000e+02 8.20958984e+02 1.00810000e+06 8.15489990e+02]
 [8.19359985e+02 8.23000000e+02 1.18810000e+06 8.18469971e+02]
 [8.19000000e+02 8.23000000e+02 1.19810000e+06 8.16000000e+02]
 [8.11700012e+02 8.15250000e+02 1.09810000e+06 8.09780029e+02]
 [8.09510010e+02 8.16659973e+02 1.39810000e+06 8.04539978e+02]]
[[831.659973]
 [828.070007]
 [824.159973]
 [819.23999 ]
 [818.97998 ]
 [820.450012]
 [813.669983]
 [809.559998]]


In [5]:
model = Sequential()
model.add(Dense(1, input_dim=4))
model.add(Activation('linear'))

model.compile(loss='mse',
              optimizer=SGD(lr=1e-5),
              metrics=['accuracy'])
model.summary()

W0314 18:48:36.630052  9948 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0314 18:48:36.651988  9948 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0314 18:48:36.654981  9948 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0314 18:48:36.683902  9948 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [6]:
history = model.fit(x_data, y_data, epochs=100)

W0314 18:48:44.320136  9948 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

W0314 18:48:44.338540  9948 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1020: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Epoch 1/100
8/8 [==============================] - 0s 11ms/step - loss: 83229458432.0000 - acc: 0.0000e+00
Epoch 2/100
8/8 [==============================] - 0s 0us/step - loss: 91442484174994134282534912.0000 - acc: 0.0000e+00
Epoch 3/100
8/8 [==============================] - 0s 715us/step - loss: inf - acc: 0.0000e+00
Epoch 4/100
8/8 [==============================] - 0s 131us/step - loss: inf - acc: 0.0000e+00
Epoch 5/100
8/8 [==============================] - 0s 109us/step - loss: inf - acc: 0.0000e+00
Epoch 6/100
8/8 [==============================] - 0s 0us/step - loss: inf - acc: 0.0000e+00
Epoch 7/100
8/8 [==============================] - 0s 859us/step - loss: nan - acc: 0.0000e+00
Epoch 8/100
8/8 [==============================] - 0s 382us/step - loss: nan - acc: 0.0000e+00
Epoch 9/100
8/8 [==============================] - 0s 259us/step - loss: nan - acc: 0.0000e+00
Epoch 10/100
8/8 [==============================] - 0s 249us/step - loss: nan - acc: 0.0000e+00
Epoch 11/100


8/8 [==============================] - 0s 249us/step - loss: nan - acc: 0.0000e+00
Epoch 87/100
8/8 [==============================] - 0s 124us/step - loss: nan - acc: 0.0000e+00
Epoch 88/100
8/8 [==============================] - 0s 192us/step - loss: nan - acc: 0.0000e+00
Epoch 89/100
8/8 [==============================] - 0s 249us/step - loss: nan - acc: 0.0000e+00
Epoch 90/100
8/8 [==============================] - 0s 249us/step - loss: nan - acc: 0.0000e+00
Epoch 91/100
8/8 [==============================] - 0s 264us/step - loss: nan - acc: 0.0000e+00
Epoch 92/100
8/8 [==============================] - 0s 125us/step - loss: nan - acc: 0.0000e+00
Epoch 93/100
8/8 [==============================] - 0s 125us/step - loss: nan - acc: 0.0000e+00
Epoch 94/100
8/8 [==============================] - 0s 125us/step - loss: nan - acc: 0.0000e+00
Epoch 95/100
8/8 [==============================] - 0s 125us/step - loss: nan - acc: 0.0000e+00
Epoch 96/100
8/8 [==============================] - 0

In [7]:
predictions = model.predict(x_data)
score = model.evaluate(x_data, y_data)

8/8 [==============================] - 0s 2ms/step


In [8]:
print('Prediction: ', predictions)
print('Accuracy: ', score[1])

Prediction:  [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Accuracy:  0.0
