In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
from sklearn.preprocessing import MinMaxScaler
import numpy as np
np.random.seed(2020)  # for reproducibility

Using TensorFlow backend.
C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [2]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [3]:
# very important. It does not work without it.
scaler = MinMaxScaler(feature_range=(0, 1))
xy = scaler.fit_transform(xy)
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [4]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [5]:
print(x_data)
print(y_data)

[[1.         1.         0.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783]
 [0.54412549 0.50274824 0.57608696 0.60646801]
 [0.33890353 0.31368023 0.10869565 0.45989134]
 [0.51436    0.4258239  0.30434783 0.58504805]
 [0.49556179 0.4258239  0.31521739 0.48131134]
 [0.11436064 0.         0.20652174 0.22007776]
 [0.         0.07747099 0.5326087  0.        ]]
[[1.        ]
 [0.83755792]
 [0.6606331 ]
 [0.43800918]
 [0.42624401]
 [0.49276137]
 [0.18597238]
 [0.        ]]


In [6]:
model = Sequential()
model.add(Dense(1, input_dim=4))
model.add(Activation('linear'))

model.compile(loss='mse',
              optimizer=SGD(lr=1e-5),
              metrics=['accuracy'])
model.summary()

W0314 18:50:18.174100 11596 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0314 18:50:18.192505 11596 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0314 18:50:18.195533 11596 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0314 18:50:18.225188 11596 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [7]:
history = model.fit(x_data, y_data, epochs=100)

W0314 18:50:18.342107 11596 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

W0314 18:50:18.355230 11596 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1020: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Epoch 1/100
8/8 [==============================] - 0s 12ms/step - loss: 1.1804 - acc: 0.1250
Epoch 2/100
8/8 [==============================] - 0s 121us/step - loss: 1.1804 - acc: 0.1250
Epoch 3/100
8/8 [==============================] - 0s 244us/step - loss: 1.1803 - acc: 0.1250
Epoch 4/100
8/8 [==============================] - 0s 174us/step - loss: 1.1802 - acc: 0.1250
Epoch 5/100
8/8 [==============================] - 0s 246us/step - loss: 1.1801 - acc: 0.1250
Epoch 6/100
8/8 [==============================] - 0s 253us/step - loss: 1.1800 - acc: 0.1250
Epoch 7/100
8/8 [==============================] - 0s 250us/step - loss: 1.1799 - acc: 0.1250
Epoch 8/100
8/8 [==============================] - 0s 125us/step - loss: 1.1799 - acc: 0.1250
Epoch 9/100
8/8 [==============================] - 0s 125us/step - loss: 1.1798 - acc: 0.1250
Epoch 10/100
8/8 [==============================] - 0s 249us/step - loss: 1.1797 - acc: 0.1250
Epoch 11/100
8/8 [==============================] - 0s 252us

Epoch 88/100
8/8 [==============================] - 0s 247us/step - loss: 1.1732 - acc: 0.1250
Epoch 89/100
8/8 [==============================] - 0s 125us/step - loss: 1.1731 - acc: 0.1250
Epoch 90/100
8/8 [==============================] - 0s 125us/step - loss: 1.1730 - acc: 0.1250
Epoch 91/100
8/8 [==============================] - 0s 125us/step - loss: 1.1729 - acc: 0.1250
Epoch 92/100
8/8 [==============================] - 0s 250us/step - loss: 1.1728 - acc: 0.1250
Epoch 93/100
8/8 [==============================] - 0s 125us/step - loss: 1.1727 - acc: 0.1250
Epoch 94/100
8/8 [==============================] - 0s 317us/step - loss: 1.1727 - acc: 0.1250
Epoch 95/100
8/8 [==============================] - 0s 124us/step - loss: 1.1726 - acc: 0.1250
Epoch 96/100
8/8 [==============================] - 0s 249us/step - loss: 1.1725 - acc: 0.1250
Epoch 97/100
8/8 [==============================] - 0s 125us/step - loss: 1.1724 - acc: 0.1250
Epoch 98/100
8/8 [==============================] 

In [8]:
predictions = model.predict(x_data)
score = model.evaluate(x_data, y_data)

8/8 [==============================] - 0s 2ms/step


In [9]:
print('Prediction: ', predictions)
print('Accuracy: ', score[1])

Prediction:  [[-0.7839926 ]
 [-0.77827007]
 [-0.5383365 ]
 [-0.30706802]
 [-0.41595143]
 [-0.39159116]
 [-0.06894486]
 [-0.18449864]]
Accuracy:  0.125
