In [7]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import Adam
from keras import initializers
from keras.utils import np_utils
from keras import backend as K
import keras

from keras.datasets import mnist

In [8]:
# parameters
learning_rate = 0.001
batch_size = 100
training_epochs = 15
nb_classes = 10

In [9]:
# input image dimensions
img_rows, img_cols = 28, 28

In [10]:
# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [12]:
if K.common.image_dim_ordering() == 'th':
    X_train = X_train.reshape(X_train.shape[0], img_rows * img_cols)
    X_test = X_test.reshape(X_test.shape[0], img_rows * img_cols)
else:
    X_train = X_train.reshape(X_train.shape[0], img_rows * img_cols)
    X_test = X_test.reshape(X_test.shape[0], img_rows * img_cols)

In [13]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

X_train shape: (60000, 784)
60000 train samples
10000 test samples


In [14]:
# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)
print(Y_train[:5])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
model = Sequential()
model.add(Dense(units=nb_classes, input_dim=img_rows * img_cols,
                kernel_initializer=initializers.random_normal(stddev=0.01),
                use_bias=True))
model.add(Activation('softmax'))

adam = Adam(lr=learning_rate)
model.compile(loss='categorical_crossentropy',
              optimizer=adam,
              metrics=['accuracy'])
model.summary()

W0314 19:00:24.391249 15100 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0314 19:00:24.408205 15100 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0314 19:00:24.411184 15100 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4409: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0314 19:00:24.439584 15100 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0314 19:00:24.447667 15100 deprecation_wrapper.py:119] From C:\Users\Admin\Anacon

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                7850      
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(X_train, Y_train, batch_size=batch_size, epochs=training_epochs)

W0314 19:00:30.560538 15100 deprecation.py:323] From C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0314 19:00:30.619334 15100 deprecation_wrapper.py:119] From C:\Users\Admin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/15
60000/60000 [==============================] - 1s 16us/step - loss: 0.6145 - acc: 0.8600
Epoch 2/15
60000/60000 [==============================] - 1s 13us/step - loss: 0.3443 - acc: 0.9060
Epoch 3/15
60000/60000 [==============================] - 1s 14us/step - loss: 0.3085 - acc: 0.9145
Epoch 4/15
60000/60000 [==============================] - 1s 15us/step - loss: 0.2918 - acc: 0.9183
Epoch 5/15
60000/60000 [==============================] - 1s 14us/step - loss: 0.2811 - acc: 0.9215
Epoch 6/15
60000/60000 [==============================] - 1s 14us/step - loss: 0.2744 - acc: 0.9237
Epoch 7/15
60000/60000 [==============================] - 1s 14us/step - loss: 0.2691 - acc: 0.9253
Epoch 8/15
60000/60000 [==============================] - 1s 15us/step - loss: 0.2649 - acc: 0.9267
Epoch 9/15
60000/60000 [==============================] - 1s 14us/step - loss: 0.2616 - acc: 0.9268
Epoch 10/15
60000/60000 [==============================] - 1s 13us/step - loss: 0.2585 - acc: 0.9284

In [17]:
score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Test score: 0.26366662853956224
Test accuracy: 0.9277
